version: '2'
services:
  coderecordapplication-app:
    image: coderecordapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://coderecordapplication-mysql:3306/coderecordapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://coderecordapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://coderecordapplication-elasticsearch:9200
    ports:
      - 8080:8080
  coderecordapplication-mysql:
    extends:
      file: mysql.yml
      service: coderecordapplication-mysql
  coderecordapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: coderecordapplication-elasticsearch
